#!/bin/bash
model_name=$1
MACHINE=$2

echo $model_name

#for MACHINE in $(docker-machine ls --format '{{.Name}}')
#do 
	#docker-machine ssh $MACHINE 'sudo -i s3cmd get --force s3://modelstorage/dynamic.rds /models/dynamic.rds' 
	docker-machine ssh $MACHINE "sudo -i s3cmd get --force s3://lucerna/$model_name /models/dynamic.rds"
	docker-machine ssh $MACHINE 'cd /api && sudo docker-compose down'
	#docker-machine ssh $MACHINE 'cd /api && sudo docker-compose build'
	docker-machine ssh $MACHINE 'cd /api && sudo docker-compose up -d --scale api=4'
#done

echo 'complete'
